Feature/imprement-door
Dangkeys/OneInsideGame pull request #10
Opened 2024-12-27 13:57 UTC by LuisPaprika

Imprement Door
Imprement Vent
Imprement Pickup Object

2024-12-30 02:13 UTC, Dangkeys requested changes
ฝากดึงจากdevelopล่าสุดให้ด้วยนะkrub

2024-12-30 02:13 UTC, Dangkeys commented on Assets/Scripts/Core/Interactable Object/BaseballBat/batHit.cs
> +public class batHit : MonoBehaviour, IInteractable
แก้เป็นNetworkBehaviour ชื่อclassต้องเริ่มต้นด้วยพิมใหญ่

2024-12-30 02:13 UTC, Dangkeys commented on Assets/Scripts/Core/Interactable Object/BaseballBat/pickupObj.cs
> +public class pickupObj : MonoBehaviour
แก้เป็นNetworkBehaviour ชื่อclassต้องเริ่มต้นด้วยพิมใหญ่

2024-12-30 02:13 UTC, Dangkeys commented on Assets/Scripts/Core/Interactable Object/SlidingDoor/slideDoor.cs
> +public class slideDoor : NetworkBehaviour, IInteractable
ชื่อclassต้องเริ่มต้นด้วยพิมใหญ่

2025-01-04 10:28 UTC, LuisPaprika commented on Assets/Scripts/Core/Interactable Object/BaseballBat/pickupObj.cs
> +public class pickupObj : MonoBehaviour
Done!

2025-01-04 10:29 UTC, LuisPaprika commented on Assets/Scripts/Core/Interactable Object/SlidingDoor/slideDoor.cs
> +public class slideDoor : NetworkBehaviour, IInteractable
Done!

2025-01-05 13:17 UTC, LuisPaprika commented on Assets/Scripts/Core/Interactable Object/BaseballBat/batHit.cs
> +public class batHit : MonoBehaviour, IInteractable
Done

2025-01-05 13:28 UTC, LuisPaprika commented
Proof Of Work Krub https://jam.dev/c/20b59d12-5011-46fc-b4ba-0b93c6d0b6fa

2025-01-07 13:22 UTC, Dangkeys approved these changes

2025-01-07 13:22 UTC, merged