Fix/quest bug
Dangkeys/OneInsideGame pull request #12
Opened 2024-12-28 10:03 UTC by billza555

Video : [https://jam.dev/c/65eee745-a958-484c-ba51-ee5276ef1da7](https://jam.dev/c/65eee745-a958-484c-ba51-ee5276ef1da7)

2024-12-28 15:15 UTC, Dangkeys commented
![image2](https://github.com/user-attachments/assets/9d576eb5-dfb7-4217-98a4-56117540a110)
![image](https://github.com/user-attachments/assets/e5e92f74-9320-46c2-b15f-a6ce98c46fbd)

progressbarอันใหญ่มันลดอ่ะพี่ แก้ให้มันไม่ลดหน่อยนะ แล้วก็ย้ายprogressbarของแต่ละquestไว้กลางล่างน่าจะดีกว่า(ref: dead by daylight)

2024-12-28 15:45 UTC, Dangkeys requested changes

2024-12-28 15:45 UTC, Dangkeys commented on Assets/Scripts/Quest/QuestSystem.cs
>      private NetworkVariable<int> QuestFinished = new NetworkVariable<int>(0);
ชื่อcompletedQuestCountน่าจะclearกว่า

2024-12-28 15:45 UTC, Dangkeys commented on Assets/Scripts/Quest/QuestSystem.cs
> +    [SerializeField] private int MaxQuest;
maxQuestCount

2024-12-28 15:45 UTC, Dangkeys commented on Assets/Scripts/Quest/QuestSystem.cs
> +    private NetworkVariable<List<int>> QuestNotUse = new NetworkVariable<List<int>>(new List<int>());
unusedQuests

2024-12-28 15:45 UTC, Dangkeys commented on Assets/Scripts/Quest/QuestSystem.cs
> +    private void QuestNotToSee()
DeactivateUnusedQuests

2024-12-28 15:45 UTC, Dangkeys commented on Assets/Scripts/Quest/QuestSystem.cs
> +    private void QuestNotToSeeClientRpc()
DeactivateUnusedQuestsClientRPC

2024-12-28 15:45 UTC, Dangkeys commented on Assets/Scripts/Quest/QuestSystem.cs
> +    [ServerRpc(RequireOwnership = false)]
DeactivateUnusedQuestsServerRpc

2024-12-28 15:45 UTC, Dangkeys commented on Assets/Scripts/Quest/QuestSystem.cs
ฝากแก้ พิมใหญ่ พิมเล็กของvariableด้วย ถ้าclassอื่นอ่านค่านี้ไม่ได้ (เป็น private) จะเป็นcamel case ถ้าclassอื่นอ่านค่านี้ได้ (เป็น public หรือ พวก Properties ) เป็นPascal

2025-01-01 16:07 UTC, billza555 commented
Video : [https://jam.dev/c/9801179c-9f7d-4fe8-bd43-fe2057f784aa](https://jam.dev/c/9801179c-9f7d-4fe8-bd43-fe2057f784aa)

2025-01-01 16:23 UTC, merged