feat: create quest dodge
Dangkeys/OneInsideGame pull request #8
Opened 2024-12-25 11:06 UTC by billza555

2024-12-25 11:06 UTC, billza555 commented
Video : https://jam.dev/c/c1f775c6-7b66-4811-9501-02fbfc743dac[https://jam.dev/c/c1f775c6-7b66-4811-9501-02fbfc743dac](url)

2024-12-25 17:00 UTC, Dangkeys requested changes

2024-12-25 17:00 UTC, Dangkeys commented on Assets/Scripts/Quest/QuestSpaceDodge/Meteorite.cs
> +        NewSpawn();
มีNewSpawn() ทั้งในawake ทั้งonenable มันไม่ซ้อนกันหรอ

2024-12-25 17:00 UTC, Dangkeys commented on Assets/Scripts/Quest/QuestSpaceDodge/QuestDodgeManager.cs
> +    public event System.Action<bool> OnWin;
เปลี่ยนเป็น OnFinishQuest ให้หน่อย

2024-12-26 12:13 UTC, Dangkeys approved these changes

2024-12-26 12:14 UTC, merged